name: mysteriouscoder
description: "Mysterious Coder Official Website"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # animations
  lottie: ^3.1.3                             # For using Lottie animations
  rive: ^0.13.10                             # For using Rive animations
  
  flutter_svg: ^1.1.5                        # For using SVG images
  flutter_email_sender: ^6.0.3               # For sending emails
  flutter_icon_snackbar: ^1.1.4              # For showing animated snackbar with icons
  icons_launcher: ^3.0.0                     # For setting app launcher icon in ios and android
  font_awesome_flutter: ^10.5.0              # For using More icons
  shimmer: ^3.0.0                            # For showing shimmer effect
  google_fonts: 6.2.1                        # For using Google Fonts
  url_launcher: ^6.1.12
  provider: ^6.1.2
  carousel_slider: ^5.0.0                    # For using carousel slider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/icons/
      - assets/animation/gifs/
icons_launcher:
  image_path: "assets/images/mysteriouscoder_logo.png"
  adaptive_icon_background: "#FFFFFF"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true