name: mysteriouscoder
description: "Mysterious Coder Official Website"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # animations
#  lottie: ^3.1.3                             # For using Lottie animations
#  rive: ^0.13.10                             # For using Rive animations
  
  flutter_svg: ^2.0.17                        # For using SVG images
  flutter_email_sender: ^7.0.0               # For sending emails
  flutter_icon_snackbar: ^1.1.4              # For showing animated snackbar with icons
  icons_launcher: ^3.0.0                     # For setting app launcher icon in ios and android
  font_awesome_flutter: ^10.5.0              # For using More icons
#  shimmer: ^3.0.0                            # For showing shimmer effect
  google_fonts: 6.2.1                        # For using Google Fonts
  url_launcher: ^6.1.12                      # For launching URLs
  provider: ^6.1.2                           # For state management
  carousel_slider: ^5.0.0                    # For using carousel slider
  intl_phone_field: ^3.2.0                   # For using international country code field
#  flutter_spinkit: ^5.2.1                   # For using loading spinners
  flutter_native_splash: ^2.4.4              # For setting splash screen
  animated_text_kit: ^4.2.3                  # For using animated text

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
      - assets/images/
      - assets/images/projects/
      - assets/icons/
      - assets/icons/projects/
      - assets/animation/gifs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

icons_launcher:
  image_path: "assets/icons/circular_mysterious_coder.png"
  adaptive_icon_background: "#FFFFFF"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    web:
      enable: true

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/circular_mysterious_coder.png"
  android: true
  ios: true
  web: true
  android_12:
    color: "#FFFFFF"
    image: "assets/icons/circular_mysterious_coder.png"